"""
Fetch country codes from GeoNames
and generate covid_world_scraper/country_codes.py
"""
from pathlib import Path
from string import Template

import requests


def main():
    url = "https://download.geonames.org/export/dump/countryInfo.txt"
    response = requests.get(url)
    front_matter, data = response.text.split("#ISO")
    rows = [
        row.strip().split('\t')
        for row in data.split("\n")
        if row.strip()
    ]
    headers = rows.pop(0)
    headers.insert(0, 'ISO')
    outfile = str(
        Path(__file__)\
            .absolute()\
            .parent\
            .parent\
            .joinpath('covid_world_scraper/country_codes.py')
    )
    with open(outfile, 'w') as mod:
        template = Template("    '$iso3': '$name',\n")
        mod.write("# DO NOT MODIFY THIS FILE MANUALLY\n")
        mod.write("# This module is generated by scripts/refresh_country_codes.py\n\n")
        mod.write("COUNTRY_CODES = {\n")
        for row in rows:
            iso3 = row[1].strip()
            name = row[4].strip()
            key_val = template.substitute(iso3=iso3, name=name)
            mod.write(key_val)
        mod.write("}\n")

if __name__ == '__main__':
    main()
